sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_15a61a882a2f_key -iv $encrypted_15a61a882a2f_iv -in multi-k8s-275916-d260ce290081.json.enc -out multi-k8s-275916-d260ce290081.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
