sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_15a61a882a2f_key -iv $encrypted_15a61a882a2f_iv -in multi-k8s-275916-d260ce290081.json.enc -out multi-k8s-275916-d260ce290081.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-275916-d260ce290081.json
  - gcloud config set project multi-k8s-275916
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_TRAVIS_K8S_TOKEN" | docker login -u "DOCKER_USERNAME" --password-stdin
  - docker build -t tarabet/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tarabet/client-test npm test
